### ISSUE TITLE
提供的验证集文件和测试集文件中的图片数量与文献中描述的不一致，是否弄混了验证集和测试集？

### ISSUE THREAD

**Issue by tdyangbo** [jaychempan/SWAN-pytorch#1]
您好，请问RSITMD的验证集和测试集是否弄混了？文献中对RSITMD数据集的描述是“We follow [29, 32] in dividing the two datasets, 7,862 training images, 1,966 validation images, and 1,093 test images on RSICD and 3,435 training images, 452 validation images, and 856 test images on RSITMD”  但是github的文件里，val_filename_verify.txt包含856个不重复的图片名，test_filename.txt包含452个不重复的图片名，与文献中验证集、测试集的数据量正好相反，从图片数量上看，好像弄混了验证集和测试集。

**Comment by jaychempan** [comment]
感谢您的细心指出，关于RSITMD在论文中时出现的错误：实际上应该是856 validation images, and 452 test images。在后续工作中将会订正。
