### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'shard_dis_MSSF‘

### ISSUE THREAD

**Issue by yuanpf123** [jaychempan/SWAN-pytorch#4]
engine.py中调用了两次utils.shard_dis_MSSF'和一次utils.shard_dis_SWAN
但是在utilts中就只有shard_dis_SWAN没有‘shard_dis_MSSF'
一下为报错信息

Traceback (most recent call last):
  File "train.py", line 461, in <module>
    main(args_new)
  File "train.py", line 194, in main
    rsum, all_scores = engine.validate(args, val_loader, model)
  File "/home/u2023170732/SWAN-pytorch/engine.py", line 135, in validate
    d = utils.shard_dis_MSSF(args, input_visual, input_text, model,
AttributeError: module 'utils' has no attribute 'shard_dis_MSSF'

**Comment by jaychempan** [comment]
将shard_dis_MSSF改成shard_dis_SWAN即可，这是是一个方法，最终的时候删除错误了。
