### ISSUE TITLE
文本编码的vocab_size

### ISSUE THREAD

**Issue by zzl0107** [jaychempan/SWAN-pytorch#5]
您好，请问一下对单词编码时的vocab_size为什么是8590？

**Comment by jaychempan** [comment]
> 您好，请问一下对单词编码时的vocab_size为什么是8590？

这里用了nn.Embedding函数（https://blog.csdn.net/lsb2002/article/details/132993128），会加载一个预训练的词汇表，然后再映射成指定大小的emb
